### ISSUE TITLE
Fingerprint sensor does not work

### ISSUE THREAD

**Issue by b100dian** [sailfishos-on-tucana/Readme#19]
Needs at least https://github.com/piggz/sailfish-fpd-community

**Comment by JamiKettunen** [comment]
You're on the right track, build that along with the `droid-biometry-fp` HAL part (instructions in [the README](https://github.com/piggz/sailfish-fpd-community#readme)), then modify your `droid-config-$DEVICE`'s `patterns/patterns-sailfish-device-configuration-$DEVICE.inc` like so:
```spec
# Enable device lock and allow to select untrusted software
#Requires: jolla-devicelock-daemon-encsfa

# Fingerprint unlocking daemon for community ports
Requires: sailfish-fpd-community
Requires: sailfish-devicelock-fpd
Requires: droid-biometry-fp
```

**Comment by b100dian** [comment]
@JamiKettunen this is most kind of you - I really appreciate you taking the time to suggest solutions for bugs on this repo!. The fpd was one of the things that I left far in the future since I need more basic stuff to work first, but definitely this gives me a boost in the time I'll be able to implement this. 👍

**Comment by b100dian** [comment]
Another worry about fingerpring on this device is that an app drawing over other apps would be needed to light up the place where the FOD is under the screen.

**Comment by b100dian** [comment]
Partially solved with:
* fpd community fork that uses inscreen service from lineage https://github.com/sailfishos-open/sailfish-fpd-community/compare/master...b100dian:master (this may work only on xiaomi devices, some vendor messages may not be portable)
* fpd test app fork that draws a bright circle where the FOD is
* TODO: need to patch the unlock screen to display the bright circle

**Comment by b100dian** [comment]
Patch uploaded https://coderus.openrepos.net/pm2/project/patch-lockscreen-touchArea
