### ISSUE TITLE
Storage browser shows too many invalid partitions

### ISSUE THREAD

**Issue by b100dian** [sailfishos-on-tucana/Readme#21]
![Screenshot_20210623_001](https://user-images.githubusercontent.com/71930/123067875-0d299800-d41a-11eb-86d0-94dc57a797ae.png)

**Comment by JamiKettunen** [comment]
Check out [a patch like this for nemo-qml-plugin-systemsettings](https://github.com/sailfishos-oneplus5/nemo-qml-plugin-systemsettings/commit/45ff551), it's sad that something like this is hard-coded in source code :(

**Comment by b100dian** [comment]
Thanks @JamiKettunen!

**Comment by b100dian** [comment]
Fixed with https://github.com/sailfishos-on-tucana/nemo-qml-plugin-systemsettings/tree/0.5.73.tucana

**Comment by b100dian** [comment]
https://github.com/sailfishos/nemo-qml-plugin-systemsettings/commits/jb51960 

@jamikettunen
