### ISSUE TITLE
calls are not routed to bluetooth

### ISSUE THREAD

**Issue by b100dian** [sailfishos-on-tucana/Readme#23]

**Comment by JamiKettunen** [comment]
For Snapdragon 835 devices at least there is [a workaround](https://github.com/sailfishos-oneplus5/droid-config-cheeseburger/commit/54767ad), perhaps it's applicable for 730G devices as well?

**Comment by b100dian** [comment]
This would be awesome:) I'll tr to understand what that does in report back

**Comment by b100dian** [comment]
This might have been more basic, I am missing this https://github.com/sailfishos-oneplus5/droid-config-cheeseburger/commit/2c03f29e167daa158f3825c265ed36eeddcdabb6#diff-9e7af1b5f0acd02a60edc581c2cc7477d48554d03e437bc9f113ca4e910cb3d5R12

**Comment by b100dian** [comment]
Fixed with https://github.com/sailfishos-on-tucana/droid-config-tucana/commit/bc8995a25a7bd8d0d5deea89bb85d4717c3c6910
