### ISSUE TITLE
MTP does not work

### ISSUE THREAD

**Issue by b100dian** [sailfishos-on-tucana/Readme#24]

**Comment by JamiKettunen** [comment]
You likely need to tell usb-moded to use different ConfigFS nodes; something like this under your `droid-config-$DEVICE` repo should get you started ([mine for reference](https://github.com/sailfishos-oneplus5/droid-config-cheeseburger)):
`rpm/droid-config-$DEVICE.spec`:
```sh
# Device-specific usb-moded configuration
Provides: usb-moded-configs
Obsoletes: usb-moded-defaults
```

`sparse/etc/usb-moded/10-setup-configfs.ini`:
```sh
[configfs]
gadget_conf_directory = configs/c.1
function_rndis        = rndis.usb0 
```

For the last one you need to confirm these match for you under `/config` (or perhaps `/sys/kernel/config`)

**Comment by b100dian** [comment]
Thank you, I will look into this, - might also be related with [this kernel change ](https://github.com/b100dian/Xiaomi_Kernel_OpenSource/commit/a4a07009e4e527615deba28c5d36de5ea24d2280)made initially to get telnet access

**Comment by b100dian** [comment]
Fixed with https://github.com/sailfishos-on-tucana/droid-config-tucana/commit/4fa26a784a57a739acc127eed0d3c866eae312e9#diff-d7af78c1f4c4a2defc54302095df328cc37c57ae94b7b45fb62a1a437eb3dcc3
Thanks Jami!
