### ISSUE TITLE
Infrared doesn't work

### ISSUE THREAD

**Issue by b100dian** [sailfishos-on-tucana/Readme#8]
irremote only 32 bit
built irremote 64 bit -> doesn't work

**Comment by b100dian** [comment]
It just need a chgrp input /dev/lirc0 somewhere

**Comment by JamiKettunen** [comment]
> It just need a chgrp input /dev/lirc0 somewhere

A [udev rule](https://www.thegeekdiary.com/how-to-configure-device-file-owner-group-with-udev-rules) would be what you're looking for, make something like `/etc/udev/rules.d/61-lirc0.rules`:
```sh
KERNEL=="lirc0", GROUP="input"
```

**Comment by b100dian** [comment]
I think I've tested an udev rule already - my recollection is that some .sh from the init*.rc files is changing the lirc device on late init, I need to re-check. If not, even writing a small systemd service could do the job.

**Comment by b100dian** [comment]
Fixed with https://github.com/sailfishos-on-tucana/droid-config-tucana/commit/ff6d9544414663af9de51f7c103f37e31a677a0e
